In [2]:
import csv
import numpy as np
import pandas as pd


def writer(name, a) :
    with open(('answ_'+str(name)+'.txt'), 'w') as w :
        w.write(str(a))

In [3]:
train = pd.read_csv('abalone.csv.csv')

train.head()
# train['AXP'].shape

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [4]:
train['Sex'] = train['Sex'].map(lambda x: 1 if x=='F' else 0)
train.head()

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,0,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,0,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [60]:
y_train = train['Rings']
X_train = pd.DataFrame(train.iloc[:,:-1]) 
X_train

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight
0,0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500
1,0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700
2,1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100
3,0,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550
4,0,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550
...,...,...,...,...,...,...,...,...
4172,1,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490
4173,0,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605
4174,0,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080
4175,1,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960
4176,0,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950

In [61]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold, cross_val_score

n_est = range(1,51)
list_score = []

for i in n_est:
    est = RandomForestRegressor(n_estimators=i, random_state=1)
    cv = KFold(n_splits = 5, random_state=1, shuffle = True)
    score = cross_val_score(est, X_train, y_train, cv=cv, scoring="r2").mean()
    list_score.append(score)

In [62]:
list_score

[0.08706436812527044,
 0.31137895621293765,
 0.3941859636885929,
 0.44156857254859083,
 0.4619435479779671,
 0.4676728394600514,
 0.47228852090176765,
 0.47881288399569266,
 0.4845659573207863,
 0.49078128631807905,
 0.49224023463793315,
 0.4965972835201936,
 0.4999238757199585,
 0.5034747690515279,
 0.5059683611121153,
 0.507863164159241,
 0.5094600397448804,
 0.5100482409465201,
 0.5127325876333613,
 0.5120396980634279,
 0.5141753965396824,
 0.5154396890255611,
 0.5168525170413151,
 0.5181304313624336,
 0.5183929400482791,
 0.5195214133457571,
 0.5202607273989001,
 0.5213889250689367,
 0.5223644736028983,
 0.5227632564038805,
 0.5236397048823931,
 0.525029241337226,
 0.526429959976597,
 0.5262350364704707,
 0.5261143988719643,
 0.5260098342421834,
 0.5254100332267992,
 0.5252218911154956,
 0.5256049034176471,
 0.5255312319201781,
 0.5261960587492035,
 0.5263628916358882,
 0.5260951360518931,
 0.5263600394578744,
 0.5257082082229064,
 0.5257193050547471,
 0.5258699126461185,
 0.5260614414164622,
 0.5268688354857787,
 0.5275846183711748]

In [66]:
leng = {}
    
for n, score in zip(n_est,list_score):
    if score > 0.52 :
        leng[n] = score
print(min(leng.keys()))
writer(121,min(leng.keys()))

27

In [65]:
for n, score in enumerate(list_score):
    if score > 0.52:
        print(1, str(n + 1))
        break

1 27